#!/bin/sh
#
# Astro firstboot oneshot (docs/07 §3). Runs once per /data lifetime
# (after data-mount, before astrod), then stamps itself done. A factory
# reset wipes /data, so firstboot reruns afterwards — by design.
#
# Deviations from the docs/07 §3 list, all deliberate:
#   - /data growth lives in data-mount.sh (landed at M1 close-out; growth
#     must precede the mount, and data-mount owns that window)
#   - machine-id is handled by the dinit-chimera early chain + the empty
#     factory /etc/machine-id (MIGRATION-NOTES §12)
#   - SSH host keys (dev) are generated by the openssh ssh-keygen service
#   - the time floor (docs/07 §6) arrives with astrod's time handling (M3
#     phase 4)
#
# What this DOES do:
#   1. API bearer token -> /data/config/api-token (0640 root:astro-api)
#   2. initial /data/config/astro.json seeded from the image's baked
#      defaults (/etc/astro/astro-defaults.json, rendered at rootfs
#      assembly from the board TOML [api] section), owned astrod 0600 so
#      the unprivileged daemon can rewrite it atomically (tmp + rename
#      needs write on the file's directory, hence the /data/config chown)
#   3. stamps /data/.astro/{firstboot-done,schema-version}

DINIT_SERVICE=firstboot

. /usr/lib/dinit.d/early/scripts/common.sh

[ -n "$DINIT_CONTAINER" ] && exit 0

# No mounted /data (direct-boot dev disk): nothing to initialize
mountpoint -q /data || exit 0

[ -f /data/.astro/firstboot-done ] && exit 0

echo "firstboot: initializing /data (first boot of this data lifetime)" > /dev/console 2>/dev/null || :

umask 077
mkdir -p /data/config /data/.astro

# /data/config is the unprivileged daemon's working directory (docs/02
# §7): owner astrod (atomic store rewrites create+rename entries here),
# group astro-api traverse-only (0710) so socket clients can be handed
# paths under it without reading the token. The names are baked into
# /etc/passwd at image assembly (05-platform-users hook); numeric
# fallback in case name resolution is unavailable this early.
chown astrod:astro-api /data/config 2>/dev/null || chown 300:301 /data/config || :
chmod 0710 /data/config

# 1. API bearer token (docs/06 §6): 256 bits, hex
if [ ! -f /data/config/api-token ]; then
    tok=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    printf '%s\n' "$tok" > /data/config/api-token
    chown root:astro-api /data/config/api-token 2>/dev/null || :
    chmod 0640 /data/config/api-token
fi

# 2. Initial desired-state store (schema-versioned; astrod migrates
#    forward from here — docs/05 §7)
if [ ! -f /data/config/astro.json ] && [ -f /etc/astro/astro-defaults.json ]; then
    cp /etc/astro/astro-defaults.json /data/config/astro.json.tmp
    chmod 0600 /data/config/astro.json.tmp
    chown astrod /data/config/astro.json.tmp 2>/dev/null || \
        chown 300 /data/config/astro.json.tmp || :
    sync
    mv /data/config/astro.json.tmp /data/config/astro.json
fi

# 3. Stamps
echo 1 > /data/.astro/schema-version
: > /data/.astro/firstboot-done
sync

exit 0
